FROM php:7.4-cli

ARG USERNAME=app
ARG USER_UID=1000
ARG USER_GID=$USER_UID
WORKDIR /var/www/html

RUN apt update && apt install  libzip-dev \
    curl \
    gcc \
    make \
    autoconf\
    libc-dev\
    pkg-config\
    git \
    libcurl4 \
    libcurl4-openssl-dev \
    libpq-dev \
    sudo \
    postgresql-client-11 -y

RUN   curl -sL https://deb.nodesource.com/setup_14.x |  sudo bash -
RUN   apt-get install -y nodejs


RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN usermod -aG 0 $USERNAME
RUN chown -R app:app /var/www/html


RUN docker-php-ext-install  zip
RUN docker-php-ext-enable  zip
RUN pecl install xdebug
RUN pecl install igbinary
RUN pecl install redis
RUN docker-php-ext-enable igbinary
RUN docker-php-ext-enable xdebug
RUN docker-php-ext-enable redis
RUN docker-php-ext-install pgsql
RUN docker-php-ext-enable pgsql
RUN docker-php-ext-install pdo_pgsql
RUN docker-php-ext-enable pdo_pgsql


RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

USER $USERNAME


COPY docker/php.ini /usr/local/etc/php/

COPY . .
RUN  sudo npm install
RUN sudo composer install

CMD ["docker/wait-for-it.sh", "postgres", "postgres" ,"postgres"]
